dist: bionic
language: python
python: 3.9
sudo: required
services:
- docker
install:
- pip install pipenv
- pipenv sync
env:
  global:
  - PY_COLOR=1
  - ANSIBLE_FORCE_COLOR=1
  - secure: U9kmBu1HYoz8IYZD0fAY7l+2JUQyWiBeTwq9rxRqPxMqKs2qekf+2lVYDaFyAYKngZxlunMbEas/9nV4WDTQ2tkAeOBTVVnOOF6ojHWe8ugnBPd3U/88ogXZGql0n12QE29xQWw/+xIcURwF7uuy6avEqZTFfMiitmarj6hs6stRhBlETcwTQuu4WtOAO/kq4rdvYQofnmr9A6ytHWTWYSkJ2YhQhkHw623bs0i34jfCgv3NTGV8Su7IlmH096qXsUw8avjefU4JpRI+8CkgaZvJ95jFm3wb1lKNHh/DgWv8VsC8PK2bSsSIRGBzGmSVMBg4p0IioyFC80BgA2zO64DhjeQ+QU0p0PeLsTOn2otqrFWygZg80UiA181Py1cbEGm97V/vgVDKf6Dqf1wd5kERuvz8wWm6MtdhF2SYrICgSVvRYY60N85+ma+USJsyg5mPB1VftqnOX6Vp1HWbrGeMB1cmEog2c5E4HxYP6kqHv7s2aZsqConT25aEa+IVSwap9gHv7V6vNSCJn3DUzHb6tlyglkJCX9j2wn/W17COuQd1ajURixeiONF56kWUg//SgrO8lzatFw8vHaO3UIgptEQcctB24Yr7M5+uwj7BrDhlk5ZyaAeFQzgRz28PZ+Re4aFQbG5OK76CTBa0XMSGZmBw20O9VziINYriz/k=
  - secure: lJQdFIh1v9I42nn4KTBz8bW4oYyMJtsM6kDsoj0y6x10PTj93zyaPQ/iwrPeFhaI879X1R4foDf1cu9sVQxJJ8I3/Ugv/fI039LItjmGMTG+2+AeLYvlzxc/cunpnHGNmNU1UBME0TeYjNVYH1CsWIs9z6jprJ7EJ60xu+TStX3lDkkwFCA8vHJV6NZgnEDVzIbReF58C/DdBRig3xuQzzc54msvyLOsUfkOgMZlfTaovz2RyAa743gT2IbaY9IZkovwdVEDJX1MOPDp59uYvxneMPoGFk4ivjCoNTKlDNKjNhN+tWXAivxqoRsDDJn0+8KqSTs6JmBsRnqWdzF653vqIWzt0Sny2b0aOKClGq3pGzIcOT+vgBgU07Uzo47NRX77IZO1FNw5rV85A6SA0yvt5HOM2ffXPdaTlbhirmoHC74l0w+p44yPBQupjbPWBwiINZLuNV2h8EZJyALgcz0ZPHpdiLVNLjw/ygU8TVq7YPuCgwdKFxAnu88T2SR+Nl+oE2FC5dwR1VMqd8uk5qf/PKAU+UROCfZnQOl1hWFipDm0sY4Gm3kJE9XEbpHExJRapbU/v8ZUNEUiqQ9fyFqVZEEGy8FgcTGk9Gf8sMo0wIZ1CzV+hSia4GMIYVP2jXnIPnLyCm1+8D5MNKxkj5Rye8B6u8GPlNYpjAWC80o=
  - secure: NSZjV2F4NQjf2dGuIhP6bdojGTzvqmrEx5+Fv5MUEYUZghgsZm+v+InjsWnabw9Vglxn9DoUJARXcpjWfczG+ZQsTPHdV2BeXVCfsEYGT6Uh43pujiWBMAYXlJp+kLVHEm2MFBLod5hkMBFFSNBAdBaUNCQRAfnjGoE3A2FH/dICWDZU6G8LCWPoh5v03fyGogdXxaRDXV0l4m77SBeZHJHvj95RG+jWSKupZfdhVcbJarqWhiGCC5WeayyVk4q6a30EnDcOjJrX4aC52s/u2nfxrPdeaDijRVE7eZiDfl4l9GoRGUM19KKk2mTcOYbDvEHwHyTB/N0B76h8m1YxvG1w2GrGxp7Potk/O+JMZ67yl5KBXA8Uyppdl5I3eTab8DqIcmAEjPFbhr+/R40LYHiRgMC8RrVyBj5/2rrnCkAwGlV7nom6JHCfmHq5CQ7Xnob1WXx2JiSPbgDdqzYnDdlqGNEFNV/OfvcfS8FxBh2bhggIQ2O97AonY30SO7qHhKFcOE7x8mOhhD1DeFQ/V5ZrZhRgofNF//Qna4uYNvO7dvCEpTHG0TK8HzWX3HSQ51gEiw7FcNc+yddUrVb22wfoCnUTOn2W/10OytO7Pm2dNnIc7EiYBmn8yj3qBz0xAgHX+hbmpKfVctqM0Uxk9ruknsPfIUYhY8l9E6gJUdw=
  jobs:
  - DOCKER_IMAGE_BASE=debian:stretch-slim DOCKER_TAG_TO_PUBLISH=8-stretch-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:stretch-slim JDK_MAJOR=8 JDK_VERSION=8u322-b06-1~deb9u1
    DOCKER_TAG_TO_PUBLISH=8u322-stretch-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:stretch-slim JDK_MAJOR=11 JDK_VERSION=11.0.6+10-1~bpo9+1
    DOCKER_TAG_TO_PUBLISH=11.0.6-stretch-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim DOCKER_TAG_TO_PUBLISH=11-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_MAJOR=11 JDK_VERSION=11.0.14+9-1~deb10u1
    DOCKER_TAG_TO_PUBLISH=11.0.14-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim DOCKER_TAG_TO_PUBLISH=11-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=11 JDK_VERSION=11.0.14+9-1~deb11u1
    DOCKER_TAG_TO_PUBLISH=11.0.14-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:xenial DOCKER_TAG_TO_PUBLISH=9-xenial-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:xenial JDK_MAJOR=8 JDK_VERSION=8u292-b10-0ubuntu1~16.04.1
    DOCKER_TAG_TO_PUBLISH=8u292-xenial-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:xenial JDK_MAJOR=9 JDK_VERSION=9~b114-0ubuntu1 DOCKER_TAG_TO_PUBLISH=9b114-xenial-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:bionic DOCKER_TAG_TO_PUBLISH=11-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:bionic JDK_MAJOR=11 JDK_VERSION=11.0.13+8-0ubuntu1~18.04
    DOCKER_TAG_TO_PUBLISH=11.0.13-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:bionic JDK_MAJOR=8 JDK_VERSION=8u312-b07-0ubuntu1~18.04
    DOCKER_TAG_TO_PUBLISH=8u312-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal DOCKER_TAG_TO_PUBLISH=17-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=17 JDK_VERSION=17.0.1+12-1~20.04 DOCKER_TAG_TO_PUBLISH=17.0.1-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=8 JDK_VERSION=8u312-b07-0ubuntu1~20.04
    DOCKER_TAG_TO_PUBLISH=8u312-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=centos:7 JDK_MAJOR=11 JDK_VERSION=11.0.12.0.7 DOCKER_TAG_TO_PUBLISH=11.0.12.0.7-centos7-openjdk-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_MAJOR=11 JDK_VERSION=11.0.13.0.8
    DOCKER_TAG_TO_PUBLISH=11.0.13.0.8-centos8-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292-b10-3
    DOCKER_TAG_TO_PUBLISH=8u292-bullseye-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292-b10-3
    DOCKER_TAG_TO_PUBLISH=8u292-buster-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_VENDOR=adoptopenjdk JDK_MAJOR=8
    JDK_VERSION=8u292_b10 DOCKER_TAG_TO_PUBLISH=8u292-centos8-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-bullseye-corretto-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-buster-corretto-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_VENDOR=corretto JDK_MAJOR=1.8.0
    JDK_VERSION=1.8.0_302.b08 DOCKER_TAG_TO_PUBLISH=8u302-centos8-corretto-headless
script:
- pipenv run molecule test --scenario-name=${JDK_VENDOR:-default}
notifications:
  webhooks:
  - https://galaxy.ansible.com/api/v1/notifications/
deploy:
  provider: script
  script: ANSIBLE_ROLES_PATH=../ pipenv run ansible-playbook dockerhub/main.yml --extra-vars
    "docker_hub_email=${DOCKER_EMAIL} docker_hub_username=${DOCKER_USERNAME} docker_hub_password=${DOCKER_PASSWORD}
    docker_image_base=${DOCKER_IMAGE_BASE} jdk_version=${JDK_VERSION} jdk_major=${JDK_MAJOR}
    jdk_vendor=${JDK_VENDOR}  docker_tag=${DOCKER_TAG_TO_PUBLISH}"
  on:
    branch: master
    tags: true
    condition: "$JDK_VERSION"
