dist: bionic
language: python
python: 3.9
sudo: required
services:
- docker
before_script:
- wget -q https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip
  -O /tmp/packer.zip
- sudo unzip -o /tmp/packer.zip -d /usr/local/bin
install:
- pip install pipenv
- pipenv sync
env:
  global:
  - PY_COLOR=1
  - ANSIBLE_FORCE_COLOR=1
  - secure: SyuJqEsbDQNy4IxT3wGc6wOo+MBaL5AErCVCN2b4Zybp/+eh7YBnvBjFV1yBux7S31S2jdBbC2nAA3L+mrdjAa3TcPULNvUX5oIRtJxfHoTK4CbkeicWfZUd+rb8S1G4Bu6bTvFSneNxrf4fKzNiwbVtq5LLHZ0xgCbrlzn+VUsdnt5jNkLj4kID2Hvjg48INNNtNN3/dvVbEG7WUisa2Jkdd2MGOBdxBI9U/CGxPNSyKFC0ZyDoe4QBq5vCeSObSBooXFpUVae5Umf0zUM/Rxwi6ICUGw7RvSOpwki68pF6trEZIegpObehfyw8LGdqpaRvY3D7FAgLnf/fZfsp5ftBkICzn6Z2pu8X+vgMQthYmHxYfAdfmvvML790s2zFvEuEuZ92b4CMy5t7ThKrDQzszrGr9su3evYmF5Rg0IKHf99+8iRYc77G/YaRtw3pk6xOpyysADS33AVp0/uTqrR4SXSsUswYV9u6JKLnvA1mMVb9OrPpJhX53st7lmpg3mrCfebLEFDr4b3BGkK12ujFYlTkKSOkdKtkOurv7ePIN13j2oGl6JOwG1dA20PhE96kOtw5G88yYkJHLyfmVkIJ43V98g8K3bGtq5VBtTVkgWSmnQeswP8trusT1lk6NhvLDHu7VDKf13TCA5vnObol5fib1ZySsRXTfj4yxzA=
  - secure: X4H1gMdHapqJLhTaLq5siAdnYph5zEbUJZN/yGEQTAuIW7GTZF2gG1nH5OxkedZLdhjhgvBxYh/fv6QCpmd3wy/GM5rGdEntLF787354CCkUAWrDymyC46S5X1EoeuNbFZiX0OAoF7UBhOTP91OMb9rTP/pP3ZYOUYFJYCTtuq7xSlcUqBOR5pXRcRT3Z4P7yFNQPTtyIcmHxvKplbrp6FJi9eAGuvHW5rbJ+gphuhBu1yHrb4QMJvnSXFcyMfPxMIogyKIizLyAjn2CeHbfQOihZp4x/VMNeiLiuLBKfNpr2kOl5DkF2f+JEXGvztjOhAzB7e0PPHmSGoPOWxU2W15b18vXhGJgTTGB5AbnyzImTdw1Oa6omsEU7MzajReNWkw7KzcXKbqBscxXOQK1Q264glGL+AhI6N+CySbZ/XDUfprM+fqn9JrQx4OpgtIUpqAyEI3N3ko1UuJ7Yb7Qzl4XEFioUUgKzpJhtNtUyLuheHUi+8taunxYq1KtNJDzDRoo9X58OcOiULp+LW1zOWF2BbWFBOj+f2eN+WXLxIS49UxW5qcJoEh/BXDF0j/Nppw7AgzXe+LUQ4wvjT61igT1gpA5HjjIQ4VNHQkOw+fesHMNuh62UDlZoUGhRgNaunvfkp2/3ACocHfLxV+O/oqxLAYMVWqGZBv1qs9udSY=
  jobs:
  - DOCKER_IMAGE_BASE=debian:stretch-slim DOCKER_TAG_TO_PUBLISH=8-stretch-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:stretch-slim JDK_MAJOR=8 JDK_VERSION=8u302-b08-1~deb9u1 DOCKER_TAG_TO_PUBLISH=8u302-stretch-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:stretch-slim JDK_MAJOR=11 JDK_VERSION=11.0.6+10-1~bpo9+1 DOCKER_TAG_TO_PUBLISH=11.0.6-stretch-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim DOCKER_TAG_TO_PUBLISH=11-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_MAJOR=11 JDK_VERSION=11.0.12+7-2~deb10u1 DOCKER_TAG_TO_PUBLISH=11.0.12-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim DOCKER_TAG_TO_PUBLISH=11-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=11 JDK_VERSION=11.0.12+7-2 DOCKER_TAG_TO_PUBLISH=11.0.12-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:xenial DOCKER_TAG_TO_PUBLISH=9-xenial-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:xenial JDK_MAJOR=8 JDK_VERSION=8u292-b10-0ubuntu1~16.04.1 DOCKER_TAG_TO_PUBLISH=8u292-xenial-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:xenial JDK_MAJOR=9 JDK_VERSION=9~b114-0ubuntu1 DOCKER_TAG_TO_PUBLISH=9b114-xenial-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:bionic DOCKER_TAG_TO_PUBLISH=11-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:bionic JDK_MAJOR=11 JDK_VERSION=11.0.11+9-0ubuntu2~18.04 DOCKER_TAG_TO_PUBLISH=11.0.11-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:bionic JDK_MAJOR=8 JDK_VERSION=8u292-b10-0ubuntu1~18.04 DOCKER_TAG_TO_PUBLISH=8u292-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:focal DOCKER_TAG_TO_PUBLISH=14-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:focal JDK_MAJOR=14 JDK_VERSION=14.0.2+12-1~20.04 DOCKER_TAG_TO_PUBLISH=14.0.2-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=amd64/ubuntu:focal JDK_MAJOR=8 JDK_VERSION=8u292-b10-0ubuntu1~20.04 DOCKER_TAG_TO_PUBLISH=8u292-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=centos:7 JDK_MAJOR=11 JDK_VERSION=11.0.12.0.7 DOCKER_TAG_TO_PUBLISH=11.0.12.0.7-centos7-openjdk-headless
  - DOCKER_IMAGE_BASE=centos:8 JDK_MAJOR=11 JDK_VERSION=11.0.12.0.7 DOCKER_TAG_TO_PUBLISH=11.0.12.0.7-centos8-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292-b10-3 DOCKER_TAG_TO_PUBLISH=8u292-bullseye-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292-b10-3 DOCKER_TAG_TO_PUBLISH=8u292-buster-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=centos:8 JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292_b10 DOCKER_TAG_TO_PUBLISH=8u292-centos8-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1 DOCKER_TAG_TO_PUBLISH=8u302-bullseye-corretto-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1 DOCKER_TAG_TO_PUBLISH=8u302-buster-corretto-headless
  - DOCKER_IMAGE_BASE=centos:8 JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1.8.0_302.b08 DOCKER_TAG_TO_PUBLISH=8u302-centos8-corretto-headless
script:
- pipenv run molecule test --scenario-name=${JDK_VENDOR:-default}
notifications:
  webhooks:
  - https://galaxy.ansible.com/api/v1/notifications/
deploy:
  provider: script
  script: JDK_VENDOR=${JDK_VENDOR:-openjdk} packer build packer/template.json
  on:
    branch: master
    tags: true
    condition: "$JDK_VERSION"
